### ISSUE TITLE
node-jose doesn't support ES256

### ISSUE THREAD

**Issue by awatson1978** [microsoft/health-cards-validation-SDK#64] opened 2021-04-18 02:38 UTC
When I run the following code, I get an `unsupported algorithm` error.
```
let jws = await jose.JWS.createSign({alg: 'ES256'}, privateKey)
    .update(b64_encoded_payloadBuffer)
    .final()
    .then(function(result) {
        console.log('jose.JWS.createSign', result)
        return result;
    });
```

Full error looks like this:
```
**I20210417-21:12:41.580(-5)? signHealthCard.recordToSign {
I20210417-21:12:41.580(-5)?   iss: 'https://vaccine-passport.symptomatic.io',
I20210417-21:12:41.580(-5)?   nbf: 1618712021,
I20210417-21:12:41.580(-5)?   vc: {
I20210417-21:12:41.580(-5)?     '@context': [ 'https://www.w3.org/2018/credentials/v1' ],
I20210417-21:12:41.580(-5)?     type: [
I20210417-21:12:41.580(-5)?       'VerifiableCredential',
I20210417-21:12:41.581(-5)?       'https://smarthealth.cards#health-card',
I20210417-21:12:41.581(-5)?       'https://smarthealth.cards#immunization'
I20210417-21:12:41.581(-5)?     ],
I20210417-21:12:41.581(-5)?     credentialSubject: { fhirVersion: '4.0.1', fhirBundle: [Object] }
I20210417-21:12:41.581(-5)?   }
I20210417-21:12:41.581(-5)? }
I20210417-21:12:41.581(-5)? signHealthCard.vcPayloadString {"iss":"https://vaccine-passport.symptomatic.io","nbf":1618712021,"vc":{"@context":["https://www.w3.org/2018/credentials/v1"],"type":["VerifiableCredential","https://smarthealth.cards#health-card","https://smarthealth.cards#immunization"],"credentialSubject":{"fhirVersion":"4.0.1","fhirBundle":{"resourceType":"Bundle","type":"collection","entry":[{"fullUrl":"Immunization/0","resource":{"status":"completed","patient":{"display":"Candace Salinas","reference":"Patient/100"},"encounter":{"reference":"Encounter/129837645"},"date":"2021-03-05","vaccineCode":{"coding":[{"system":"CVX","code":"03"}]},"resourceType":"Immunization"}},{"fullUrl":"Immunization/0","resource":{"status":"completed","patient":{"display":"Candace Salinas","reference":"Patient/100"},"encounter":{"reference":"Encounter/129837645"},"date":"2021-03-05","vaccineCode":{"coding":[{"system":"CVX","code":"03"}]},"resourceType":"Immunization"}}]}}}}
I20210417-21:12:41.581(-5)? signHealthCard.vcPayload_Uint8Array Uint8Array(381) [
I20210417-21:12:41.581(-5)?   237, 146, 207,  78, 227,  48,  16, 198,  95, 101,  53, 123,
I20210417-21:12:41.582(-5)?    77,  19, 187, 229,  79, 201,   9,  81, 113, 224, 134, 196,
I20210417-21:12:41.582(-5)?    46,  66,  66,  61, 184, 206, 148,  26,  57, 118, 100,  79,
I20210417-21:12:41.582(-5)?   218,  45,  40, 239, 190,  51,  41,   5, 132, 180, 251,   4,
I20210417-21:12:41.582(-5)?   248, 102, 207, 231, 223, 124, 223, 216, 175, 224, 114, 134,
I20210417-21:12:41.582(-5)?    26,  54,  68,  93, 174, 171, 106, 107, 172, 117,   1,  39,
I20210417-21:12:41.582(-5)?   157, 201, 185, 139, 137, 202, 188, 111,  59, 138, 173,  33,
I20210417-21:12:41.582(-5)?   103,  75,  23, 161, 128, 176,  90,  67, 173, 207, 244, 252,
I20210417-21:12:41.582(-5)?    92,  79, 213,  84,
I20210417-21:12:41.582(-5)?   ... 281 more items
I20210417-21:12:41.582(-5)? ]
I20210417-21:12:41.583(-5)? signHealthCard.syncedCompressedRecord.b64_encoded_payloadBuffer 7ZLPTuMwEMZfZTV7TRO75U/JCVFx4IbELkJCPbjOlBo5dmRP2i0o774zKQWEtPsE+GbP599839iv4HKGGjZEXa6ramusdQEnncm5i4nKvG87iq0hZ0sXoYCwWkOtz/T8XE/VVBewtVC/wqWNgfAPQf34DtvtduVuVsb0VE2Vnlc2YYOBnPG52mpYFkD7DuXGPSa3dmblcfGu4V5HUG5Nog0aT5vSmtTkn4fNRDb/1bm27YN7YfsxSMMPC3f96hktiff1xiV2kEVTw0mpSs1QOb3qQ+NRNAlz7JPFX6NjeCscE4CN3jNNCAVwg7TnWEzuvf+dPAtuPhmpFIuOQIFnMtTnEdN2HgklVMdaJkm9cbnzhpGwMKExFn/cGe+CySNnjQmDgOD2cKXSSsEgPmzs+VXSIcCH7vpYqPT0Yj47Pzs5FX1jSKryrBM1m6hTxr99iEVsRqc2Ni48jdnyPhO24un+gYV2VICawbAciq/z+hwfhqH4Hs2/RrMceP0F
I20210417-21:12:41.598(-5)? Exception while invoking method 'signHealthCard' Error: unsupported algorithm
I20210417-21:12:41.598(-5)?     at JWKBaseKeyObject.value (/Volumes/FhirCode/Code/Covid19/vaccine-passport/packages/vaccine-wallet/.npm/package/node_modules/node-jose/lib/jwk/basekey.js:455:31)
I20210417-21:12:41.598(-5)?     at /Volumes/FhirCode/Code/Covid19/vaccine-passport/packages/vaccine-wallet/.npm/package/node_modules/node-jose/lib/jws/sign.js:142:21
I20210417-21:12:41.598(-5)?     at Array.map (<anonymous>)
I20210417-21:12:41.598(-5)?     at /Volumes/FhirCode/Code/Covid19/vaccine-passport/packages/vaccine-wallet/.npm/package/node_modules/node-jose/lib/jws/sign.js:118:21
I20210417-21:12:41.599(-5)?     at /Users/abigailwatson/.meteor/packages/promise/.0.11.2.8skplc.uqog2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20210417-21:12:41.599(-5)?  => awaited here:
I20210417-21:12:41.599(-5)?     at Function.Promise.await (/Users/abigailwatson/.meteor/packages/promise/.0.11.2.8skplc.uqog2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20210417-21:12:41.599(-5)?     at packages/symptomatic:vaccine-wallet/server/methods.js:195:16
I20210417-21:12:41.599(-5)?     at /Users/abigailwatson/.meteor/packages/promise/.0.11.2.8skplc.uqog2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```
After scouring the [node-jose](https://www.npmjs.com/package/node-jose) documentation, I can't find any mention of ES256.  

I'm uncomfortable relying on a validation tool whose libraries can't generate the cryptography that it's suppose to be validating.   How are we suppose to know this works and the results can be relied on?

**Comment by jmandel** [comment] 2021-04-18 03:57
Just to check, have you run into an issue where the validator is producing results you did not expect, or is producing an error? It would help to include your inputs as well as details about what output you received from the validator vs what you were expecting.

For an example of signing a JWS, you can check out https://github.com/smart-on-fhir/health-cards/blob/ded4dcb00d4bf2e0cac98aec6579c0dcefba6018/generate-examples/src/index.ts#L68 which is included as part of the framework specification; this demonstrates how to use the `node-jose` module for ES256 signatures (but I should note that the choice of this particular library is an implementation detail; we could just as well have chosen a different library, and in the future this could change).

From your example, two things:

* Are you sure your privateKey is of a type that supports ES256 signatures? Just to confirm, it shoudl have: "kty": "EC", "use": "sig", "alg": "ES256", "crv": "P-256".

* (Unrelated, but worth mentioning) It looks like you may be passing in base64-encoded data to the "sign" function, based on your variable names -- but you want to be passing in the buffer of compressed payload octets, not an encoded version. (This wouldn't be the cause of your error here, but it may be the cause of a future error once you have this working.)

If you want to follow the internals on `node-jose`...

*  `node-jose` handles ES256 signatures as part of its ECDSA algorithm support at https://github.com/cisco/node-jose/blob/1f86e23fc69063aea56974aa7247c2400b7dd50c/lib/algorithms/ecdsa.js#L248;

* this relies on a generic `ecdsaSignFN` function at https://github.com/cisco/node-jose/blob/1f86e23fc69063aea56974aa7247c2400b7dd50c/lib/algorithms/ecdsa.js#L25

* this function in turn relies on the underlying platform (node's [crypto module](https://nodejs.org/api/crypto.html), or [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) in a browser context) for cryptographic signing.

**Comment by christianpaquin** [comment] 2021-04-19 14:40
Per @jmandel's point, that doesn't look like an issue with the validation SDK. Can we close this, or move to discussion?

**Comment by awatson1978** [comment] 2021-04-19 18:53
Well, we’re going to need to maybe agree to disagree, as I think it _is_ an issue with the validator, in so far as the libraries it relies on are behaving inconsistently in different environments, and maybe can’t be entirely relied upon.  In particular, the way that Buffer vs Uint8Array is being handled and the need for base64 encoding and `atob/btoa` is non-standard across languages/environments, and not well documented or represented by the validator.

That being said, Josh’s comment above was extremely useful and helped me get every thing sorted out.  With the example it references, I was able to cross reference its `deflateRaw` function with the `inflateRaw` function from the validator below:

https://github.com/microsoft/health-cards-validation-SDK/blob/main/src/jws-compact.ts

My takeaway was that this style of coding is more unforgiving than UI programming, and requires generous use of `try/catch` blocks.  So, after sprinkling my code with them, I was able to test a dozen libraries in parallel in a sort of matrix analysis.  End result was that `jws` provided much more consistent signing functionality, and I was able to use Node’s native `zlib` function once we included `btoa/atob` libs.  Both `node-jose` and `pako` make assumptions around ESM support (and typescript), which in turn has implications on how Buffers are handled related to Node versions.

There are some other issues I have with the architectural/design of the validator and the spec, in so far as the need for `deflate/inflate` in general seems to me to be premature optimization and a substantial barrier to implementation and source of bugs.  But that’s an architectural/spec issue, and can be discussed in the appropriate workgroup meetings.  

Regardless, I think a good compromise would be the following:  let’s make sure a link to the example that Josh provided is included in the Readme, and then close the issue ticket.

**Comment by christianpaquin** [comment] 2021-04-19 19:42
> Regardless, I think a good compromise would be the following: let’s make sure a link to the example that Josh provided is included in the Readme, and then close the issue ticket.

Which link, the one pointing to the example generation code? This is already in [this section of the spec](https://smarthealth.cards/#what-testing-tools-are-available-to-validate-smart-health-cards-implementations). The validation spec is not meant to be a reference implementation of a health card verifier (nor an issuer), it utilizes many components to catch as many errors as we can anticipate.

I'm not sure I understand your proposed modifications to this project (vs. the spec).

**Comment by christianpaquin** [comment] 2021-04-23 19:31
No further action on SDK

**Closed by christianpaquin** 2021-04-23 19:31 UTC
